user_pref("browser.tabs.drawInTitlebar", false);
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.urlbar.update1.interventions", false);
user_pref("browser.urlbar.update1.searchTips", false);
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.searchEngines", "");
user_pref("browser.newtabpage.pinned", "");
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("font.name.monospace.x-western", "JetBrains Mono NL");
user_pref("font.name.sans-serif.x-western", "Ubuntu");
user_pref("font.name.serif.x-western", "EB Garamond");
user_pref("browser.display.use_document_fonts", 0);
user_pref("devtools.toolbox.host", "window");
user_pref("devtools.toolbox.previousHost", "bottom");
user_pref("sidebar.position_start", false);
user_pref("browser.messaging-system.whatsNewPanel.enabled", false);
user_pref("media.hardwaremediakeys.enabled", false);
user_pref("full-screen-api.transition-duration.enter", "0 0");
user_pref("full-screen-api.transition-duration.leave", "0 0");
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("dom.security.https_only_mode", true);
user_pref("extensions.activeThemeID", "{758478b6-29f3-4d69-ab17-c49fe568ed80}");
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.backspace_action", 0);
user_pref("browser.menu.showViewImageInfo", true);
user_pref("browser.compactmode.show", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.chrome.enabled", true);
