user_pref("browser.tabs.drawInTitlebar", true);
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.urlbar.update1.interventions", false);
user_pref("browser.urlbar.update1.searchTips", false);
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.searchEngines", "");
user_pref("browser.newtabpage.pinned", "");
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("font.name.monospace.x-western", "JetBrains Mono NL");
user_pref("font.name.sans-serif.x-western", "Ubuntu");
user_pref("browser.display.use_document_fonts", 0);
user_pref("devtools.toolbox.host", "window");
user_pref("devtools.toolbox.previousHost", "bottom");